name: Deploy Calcola Stipendio

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Installazione Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Installazione dipendenze
        run: npm install

      - name: Esecuzione test
        run: npm test -- --watchAll=false --coverage=false

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test  # Esegue solo se i test passano

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Installazione Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Installazione dipendenze
        run: npm install

      - name: Build dell'app
        run: CI=false npm run build

      - name: Copia file su VPS via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "build/*"
          target: "/var/www/calcola-stipendio"
          strip_components: 1 # Rimuove la cartella "build/" e mette i file direttamente nel target
